#!/usr/bin/env python3
from TTS.api import TTS

print("initializing xtts, will take time.")
# Load XTTS
tts = TTS("tts_models/multilingual/multi-dataset/xtts_v2")
tts.to("cuda")

# Vars
words = input("Enter text to be converted:\n-------------------------\n")

#words = "Why did we first decide to put candles on top of a birthday cake? It was too hard to blow them out when they were on the bottom."
fp = input("Enter file name: ")
fp = f"/home/sohfix/media/audio/default/default-podcast/podcast/knowledge/clips/{fp}.wav"

print(fp,"\nloading reference samples.")

# Multiple reference samples (list of wavs)
reference_samples = [
    "/home/sohfix/media/audio/default/default-podcast/podcast/knowledge/clips/goat.wav",
    "/home/sohfix/media/audio/default/default-podcast/podcast/knowledge/clips/tropes.wav",
    "/home/sohfix/media/audio/default/default-podcast/podcast/knowledge/clips/arrogant_princesses.wav"
]

# Generate
tts.tts_to_file(
    text=f"{words}",
    speaker_wav=reference_samples, 
    language="en",
    file_path=fp
)

print(f"Find your file at: \n{fp}")
